/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/ProjectList copy.vue')['default']
    Icon: typeof import('~icons/ic/on')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    ProList: typeof import('./src/components/ProList.vue')['default']
    ProProducts: typeof import('./src/components/ProProducts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
