/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiModelChipLayerSection: typeof import('./src/components/AIModel/AiModelChipLayerSection.vue')['default']
    AiModelEnergySection: typeof import('./src/components/AIModel/AiModelEnergySection.vue')['default']
    AiModelInfrastructureLayerSection: typeof import('./src/components/AIModel/AiModelInfrastructureLayerSection.vue')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    GitHubLink: typeof import('./src/components/GitHubLink.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    ProList: typeof import('./src/components/ProList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToggleTheme: typeof import('./src/components/ToggleTheme.vue')['default']
    WrapperPost: typeof import('./src/components/WrapperPost.vue')['default']
  }
}
