/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about-tech': RouteRecordInfo<
      '/about-tech',
      '/about-tech',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about-uni': RouteRecordInfo<
      '/about-uni',
      '/about-uni',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/': RouteRecordInfo<
      '/blogs/',
      '/blogs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/ai-model': RouteRecordInfo<
      '/blogs/ai-model',
      '/blogs/ai-model',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/coffee-performance': RouteRecordInfo<
      '/blogs/coffee-performance',
      '/blogs/coffee-performance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/ruoyi-project-conventions': RouteRecordInfo<
      '/blogs/ruoyi-project-conventions',
      '/blogs/ruoyi-project-conventions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/ruoyi-vue3': RouteRecordInfo<
      '/blogs/ruoyi-vue3',
      '/blogs/ruoyi-vue3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/vite-framework': RouteRecordInfo<
      '/blogs/vite-framework',
      '/blogs/vite-framework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/wang-editor-ruoyi': RouteRecordInfo<
      '/blogs/wang-editor-ruoyi',
      '/blogs/wang-editor-ruoyi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/blogs/weapp-dev': RouteRecordInfo<
      '/blogs/weapp-dev',
      '/blogs/weapp-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pro-products': RouteRecordInfo<
      '/pro-products',
      '/pro-products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/translations/': RouteRecordInfo<
      '/translations/',
      '/translations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/translations/get-started-with-the-Figma-MCP-server': RouteRecordInfo<
      '/translations/get-started-with-the-Figma-MCP-server',
      '/translations/get-started-with-the-Figma-MCP-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/translations/guide-to-the-Figma-MCP-server': RouteRecordInfo<
      '/translations/guide-to-the-Figma-MCP-server',
      '/translations/guide-to-the-Figma-MCP-server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/about-tech.vue': {
      routes:
        | '/about-tech'
      views:
        | never
    }
    'pages/about-uni.vue': {
      routes:
        | '/about-uni'
      views:
        | never
    }
    'pages/blogs/index.md': {
      routes:
        | '/blogs/'
      views:
        | never
    }
    'pages/blogs/ai-model.md': {
      routes:
        | '/blogs/ai-model'
      views:
        | never
    }
    'pages/blogs/coffee-performance.md': {
      routes:
        | '/blogs/coffee-performance'
      views:
        | never
    }
    'pages/blogs/ruoyi-project-conventions.md': {
      routes:
        | '/blogs/ruoyi-project-conventions'
      views:
        | never
    }
    'pages/blogs/ruoyi-vue3.md': {
      routes:
        | '/blogs/ruoyi-vue3'
      views:
        | never
    }
    'pages/blogs/vite-framework.md': {
      routes:
        | '/blogs/vite-framework'
      views:
        | never
    }
    'pages/blogs/wang-editor-ruoyi.md': {
      routes:
        | '/blogs/wang-editor-ruoyi'
      views:
        | never
    }
    'pages/blogs/weapp-dev.md': {
      routes:
        | '/blogs/weapp-dev'
      views:
        | never
    }
    'pages/demos.vue': {
      routes:
        | '/demos'
      views:
        | never
    }
    'pages/notes.vue': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/pro-products.md': {
      routes:
        | '/pro-products'
      views:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
    }
    'pages/translations/index.md': {
      routes:
        | '/translations/'
      views:
        | never
    }
    'pages/translations/get-started-with-the-Figma-MCP-server.md': {
      routes:
        | '/translations/get-started-with-the-Figma-MCP-server'
      views:
        | never
    }
    'pages/translations/guide-to-the-Figma-MCP-server.md': {
      routes:
        | '/translations/guide-to-the-Figma-MCP-server'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
